# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# crespo. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that crespo is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.



# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.
#DEVICE_PACKAGE_OVERLAYS := device/samsung/crespo/overlay

# These are the hardware-specific configuration files
PRODUCT_COPY_FILES := \
	device/beatcraft/bc10/vold.fstab:system/etc/vold.fstab

# Init files
PRODUCT_COPY_FILES += \
	device/beatcraft/bc10/init.bc10.rc:root/init.rc \
	device/beatcraft/bc10/init.omap3.rc:root/init.omap3.rc \
	device/beatcraft/bc10/ueventd.omap3.rc:root/ueventd.omap3.rc

PRODUCT_COPY_FILES += \
	device/beatcraft/bc10/init.omap3.sh:system/etc/init.omap3.sh

# gps_init.sh
#
PRODUCT_COPY_FILES += \
	device/beatcraft/bc10/gps_init.sh:root/gps_init.sh

# gps conf file
#
PRODUCT_COPY_FILES += \
	device/common/gps/gps.conf_AS:system/etc/gps.conf

# Generated kcm keymaps
PRODUCT_PACKAGES := \
	TWL4030_Keypad.kcm

PRODUCT_PACKAGES += \
	LiveWallpapersPicker \
	LiveWallpapers \
	MagicSmokeWallpapers \
	VisualizationWallpapers \
		libRS \
		librs_jni

# Filesystem management tools
#PRODUCT_PACKAGES += \
#	make_ext4fs \
#	setup_fs

#PRODUCT_CHARACTERISTICS := nosdcard

# These are the OpenMAX IL configuration files
#PRODUCT_COPY_FILES += \
#	device/samsung/crespo/sec_mm/sec_omx/sec_omx_core/secomxregistry:system/etc/secomxregistry \
#	device/samsung/crespo/media_profiles.xml:system/etc/media_profiles.xml


# These are the OpenMAX IL modules
#PRODUCT_PACKAGES += \
#	libSEC_OMX_Core \
#	libOMX.SEC.AVC.Decoder \
#	libOMX.SEC.M4V.Decoder \
#	libOMX.SEC.M4V.Encoder \
#	libOMX.SEC.AVC.Encoder

# Misc other modules
#PRODUCT_PACKAGES += \
#	sensors.bc10

# Libs
#PRODUCT_PACKAGES += \
#	libcamera \
	libstagefrighthw

# NFC
#PRODUCT_PACKAGES += \
#	libnfc \
#	libnfc_jni \
#	Nfc \
#	Tag

# Input device calibration files
#PRODUCT_COPY_FILES += \
#	device/samsung/crespo/mxt224_ts_input.idc:system/usr/idc/mxt224_ts_input.idc

# These are the hardware-specific features
PRODUCT_COPY_FILES += \
	frameworks/base/data/etc/handheld_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
	frameworks/base/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
	frameworks/base/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/base/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/base/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
     ro.sf.lcd_density=120
#    ro.opengles.version=131072

# These are the hardware-specific settings that are stored in system properties.
# Note that the only such settings should be the ones that are too low-level to
# be reachable from resources or other mechanisms.
PRODUCT_PROPERTY_OVERRIDES += \
       wifi.interface=ra0 \
       wifi.supplicant_scan_interval=15 \
       dalvik.vm.heapsize=32m

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

# Screen density is actually considered a locale (since it is taken into account
# the the build-time selection of resources). The product definitions including
# this file must pay attention to the fact that the first entry in the final
# PRODUCT_LOCALES expansion must not be a density.
PRODUCT_LOCALES := ldpi hdpi mdpi


PRODUCT_COPY_FILES += \
	device/beatcraft/bc10/rt3070sta.ko:system/lib/modules/rt3070sta.ko

PRODUCT_COPY_FILES += \
	device/beatcraft/bc10/RT2870STA.dat:system/etc/Wireless/RT2870STA/RT2870STA.dat

PRODUCT_COPY_FILES += \
	device/beatcraft/bc10/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf

#ifeq ($(TARGET_PREBUILT_KERNEL),)
#LOCAL_KERNEL := device/samsung/crespo/kernel
#else
#LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)
#endif

#PRODUCT_COPY_FILES += \
#    $(LOCAL_KERNEL):kernel

# See comment at the top of this file. This is where the other
# half of the device-specific product definition file takes care
# of the aspects that require proprietary drivers that aren't
# commonly available
#$(call inherit-product-if-exists, vendor/samsung/crespo/device-vendor.mk)
